@startuml Domain-Model-Elaborate
left to right direction

package Product <<Frame>> {
	class Product {
	  price
	  description
	  image
	}
}


package Customer <<Frame>> {

	class PostalAddress {
	  streetAddress
	  postalCode
	  addressLocality
	  addressRegion
	}
	class Customer {
	  givenName
	  familyName
	}
}

package Order <<Frame>> {

	class LineItem {
	  amount
	}
	class Order {
	  
	}
	enum ShippingMode {
	  REGULAR
	  PRIORITY
	  PICKUP
	}
	
}

Customer *-- PostalAddress
Order "shippingAddress" o-- PostalAddress
LineItem "product"  o-- Product
Order "lineItems" *-- LineItem
Order "shipping" o-- ShippingMode
Customer "orders" o-- Order

@enduml